
# Using a "slim" base image ends up being about 100MB smaller than the regular ubuntu 
#FROM ubuntu:16.04
FROM debian:stretch-slim

# Set some parameters.
ENV NODE_VERSION 15
ENV NODE_USER  app
ENV NODE_GROUP mqclient
ENV APP_DIR    /usr/local/nodejs

# Defaults for the MQ Developer Edition server container
ENV MQ_Q    DEV.QUEUE.2
ENV MQ_CHNL     DEV.ADMIN.SVRCONN
ENV MQ_CONN    localhost\(1414\)
ENV MQ_QMGR QM1
ENV MQ_USER admin
ENV MQ_PWD passw0rd

# Google account settings
ENV GOOGLE_APPLICATION_CREDENTIALS disco-stock-292311-f022353b952d.json
ENV GCP_TOP projects/disco-stock-292311/topics/from_mq

WORKDIR ${APP_DIR}

# Create the application directory so we can put stuff in there immediately
RUN mkdir -p ${APP_DIR}

# Update the base image and make sure we've installed basic capabilities
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl gcc g++ make git ca-certificates \
    && curl --silent -k --location https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - \
    && apt-get install -y  nodejs  \
#	&& apt-get install -y iputils-ping  \
#	&& apt-get install -y telnet  \
    && npm install -g npm \
# Define the userid and set up the location for the program
   && groupadd -r ${NODE_GROUP} && useradd -r -m -g ${NODE_GROUP} ${NODE_USER} 

# Copy project files into the container. In this source directory, the
# package file has been given a different name, to avoid any attempt to
# reference it with the rest of the samples. But it gets renamed to the
# correct name during this copy.
COPY mq-google-adapter/mqCToGcp.js ${APP_DIR}/
COPY /c/tmp/${GOOGLE_APPLICATION_CREDENTIALS} ${APP_DIR}/
COPY package.docker ${APP_DIR}/package.json

# Now get all the prereq packages installed and cleanup the
# pieces that are not needed after building the C interface pieces.
RUN npm install \
   && apt-get autoremove -y curl make gcc g++ python git \
   && apt-get purge -y \
   && rm -rf /var/lib/apt/lists/* \
   && chmod a+rx ${APP_DIR}/*

USER ${NODE_USER}
# Now ready to run the mqCToGcp program.
CMD node mqCToGcp ${GCP_TOP} ${MQ_Q} ${MQ_CONN} ${MQ_CHNL} ${MQ_QMGR} ${MQ_USER} ${MQ_PWD}
